Add GLM MOJO compatibility tests, add GLM to mojoland init
h2oai/mojoland pull request #17
Opened 2021-03-14 23:38 UTC by km2018

JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8041

This pull request adds MOJO compatibility checks for GLM.

2021-03-16 21:01 UTC, wendycwong requested changes

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/cars_glm_recipe.py
> +        model.train(y="mpg", training_frame=fr, ignored_columns=["name"])
Karthik: remove the argument epochs=50, that one is for deeplearning.

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/eyestate_glm_recipe.py
> +        model.train(y="eyeDetection", training_frame=fr)
Remove epochs=100, reproduci ble=True arguments.

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/iris_glm_recipe.py
> +        model.train(y="Species", training_frame=fr)
remove arguments epochs=20, reproducible=True

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/missing_glm_recipe.py
> +        model.train(training_frame=fr)
remove epochs=50, reproducible=True

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/names_glm_recipe.py
> +        model.train(y="sex", training_frame=fr)
remove epochs=100, reproducible=True

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/stars_glm_recipe.py
> +        model.train(y="distance", training_frame=fr, ignored_columns=["name1", "name2"])
remove arguments epochs=100, reproducible=True

2021-03-16 21:01 UTC, wendycwong commented on mojo-py/mojoland/recipes/glm/titanic_glm_recipe.py
> +        model.train(y="parch", training_frame=fr, ignored_columns=["name", "ticket", "boat", "home.dest"])
remove epochs=50, reproducible=True

2021-03-19 08:46 UTC, koniecsveta commented on mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars_multiparams.txt
> +2
is mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars.mojo really empty file?

2021-03-19 10:06 UTC, koniecsveta commented
to me something seems to be wrong. when I run `python mojo-py/in_mojo_veritas.py --filter glm ` I get this exception:


```
...

#----------------------------------------------------------
#  Tasting Glm Cars recipe
#----------------------------------------------------------

Tasting nibble parameters in /Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars_parameters.txt... ok
Tasting nibble multiparams in /Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars_multiparams.txt... ok
Traceback (most recent call last):
  File "mojo-py/in_mojo_veritas.py", line 40, in <module>
    connoisseur.degustate(recipe)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 39, in degustate
    self._taste(recipe, version)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 150, in _taste
    nibble_fresh = self._make_nibble(mojo, commands)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 229, in _make_nibble
    res = mojo.call(*command)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/mojo_model.py", line 27, in call
    return self._backend.invoke_method(self._id, method, params)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/backend/mojobackend.py", line 39, in invoke_method
    return self._request("GET /mojos/%s/%s" % (model_id, method), params=params)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/backend/mojobackend.py", line 162, in _request
    raise Exception("Error %d: %s\n>> Request: %s\n>> Params:  %r" %
Exception: Error 500: java.lang.IllegalAccessException: Class ai.h2o.mojos.server.core.MojoApi$ApiMethod can not access a member of class hex.genmodel.algos.glm.GlmMojoModelBase with modifiers "public final"

ai.h2o.mojos.server.core.MojoApi$ApiMethod.invoke(MojoApi.java:59)
ai.h2o.mojos.server.handlers.MojoApiHandler.executeModelMethod(MojoApiHandler.java:116)
ai.h2o.mojos.server.handlers.MojoApiHandler.getImpl(MojoApiHandler.java:53)
ai.h2o.mojos.server.handlers.BaseHandler.doGet(BaseHandler.java:20)

>> Request: GET /mojos/1/score0~dada
>> Params:  {'arg1': '[8,360,175,3821,11,73]', 'arg2': '[0, 0]'}
Closing connection _sid_bbf9 at exit
H2O session _sid_bbf9 closed.


```
while for all the other algos everything works ok.

and I get the same when I try to generate the .mojos and .txts from scratch `python mojo-py/in_mojo_veritas.py --filter glm --creative`:




```
...

#----------------------------------------------------------
#  Tasting Glm Cars recipe
#----------------------------------------------------------

Baking the recipe...
Parse progress: |█████████████████████████████████████████████████████████████████████████████| 100%
glm Model Build progress: |███████████████████████████████████████████████████████████████████| 100%

Saving the mojo to /Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars.mojo

Making nibble parameters -> /Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars_parameters.txt
Making nibble multiparams -> /Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-data/mojos/glm/cars/v1.00/glm_v1.00_cars_multiparams.txt
Traceback (most recent call last):
  File "mojo-py/in_mojo_veritas.py", line 40, in <module>
    connoisseur.degustate(recipe)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 39, in degustate
    self._taste(recipe, version)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 150, in _taste
    nibble_fresh = self._make_nibble(mojo, commands)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/recipes/connoisseur.py", line 229, in _make_nibble
    res = mojo.call(*command)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/mojo_model.py", line 27, in call
    return self._backend.invoke_method(self._id, method, params)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/backend/mojobackend.py", line 39, in invoke_method
    return self._request("GET /mojos/%s/%s" % (model_id, method), params=params)
  File "/Users/zuzanaolajcova/IdeaProjects/mojoland/mojo-py/mojoland/backend/mojobackend.py", line 162, in _request
    raise Exception("Error %d: %s\n>> Request: %s\n>> Params:  %r" %
Exception: Error 500: java.lang.IllegalAccessException: Class ai.h2o.mojos.server.core.MojoApi$ApiMethod can not access a member of class hex.genmodel.algos.glm.GlmMojoModelBase with modifiers "public final"

ai.h2o.mojos.server.core.MojoApi$ApiMethod.invoke(MojoApi.java:59)
ai.h2o.mojos.server.handlers.MojoApiHandler.executeModelMethod(MojoApiHandler.java:116)
ai.h2o.mojos.server.handlers.MojoApiHandler.getImpl(MojoApiHandler.java:53)
ai.h2o.mojos.server.handlers.BaseHandler.doGet(BaseHandler.java:20)

>> Request: GET /mojos/1/score0~dada
>> Params:  {'arg1': '[8,360,175,3821,11,73]', 'arg2': '[0, 0]'}
Closing connection _sid_8044 at exit
H2O session _sid_8044 closed.

```

Let's agree on call to compare setups and workflow.

2021-04-07 16:59 UTC, michalkurka commented
@km2018 please remove all the `.DS_Store` files, they are not needed

2021-04-14 16:16 UTC, koniecsveta approved these changes

2021-04-14 16:20 UTC, merged